### ISSUE TITLE
store.legitimoose.com is the wrong website

### ISSUE THREAD

**Issue by loglot** [LegitiDevs/website#22]
please change it to whatever domain you have

**Comment by OmriPH** [comment]
what are you talking about

**Comment by Anjo2807** [comment]
> what are you talking about
i think he's talking about that we link to a website we don't own

**Comment by PilkeySEK** [comment]
As long as we arent hosting the website anywhere yet we will keep it like this (when we have hosting we'll likely change it though)

**Comment by loglot** [comment]
> As long as we arent hosting the website anywhere yet we will keep it like this (when we have hosting we'll likely change it though)

Fair enough
